### ISSUE TITLE
Force footer to bottom of page

### ISSUE THREAD

**Issue by paniash** [paniash/paniash.github.io#1]
Currently trying to implement this using flexbox (https://css-tricks.com/couple-takes-sticky-footer/). 

With the method suggested by @tlienart:
```css
.page-foot {
  position: fixed;
  bottom: 0;
}
```

However, this only sticks the footer to the end of the page being viewed i.e. if the content is longer, then the footer floats over the content.

I've tried testing this flexbox method shown in css-tricks.com but it doesn't seem to work. I'd really appreciate your help on this @tlienart. Thanks for your time in advance!

**Comment by paniash** [comment]
Thanks a lot! However, now whenever the content is less than the viewing height, for some reason it leaves quite some vertical space between the header and the content (see pic attached).

![pic-window-230828-2328-40](https://github.com/paniash/paniash.github.io/assets/59497618/7440019d-14c1-46be-bf61-c734a5feaaac)

**Comment by paniash** [comment]
> you'll have to adjust the styling of the footer separately to `.franklin-content` now but it will be at the bottom of your page.

Do I modify that in `franklin.css` under `franklin-content`?

**Comment by tlienart** [comment]
Yeah this is because now the content is in a flex box I think.

What you can try is add an outer div in the layout so in head you'd have

```
...
<body>
<div class="outer">
```

And in foot you'd close that before the footer

```
</div>
<!-- rest of the footer stuff -->
...
</body></html>
```

Then you can make that outer div a flex as in my previous comment and the inner div (`.franklin-content`) you can make it `height:100%` so it takes the full flex box)

I haven't tried but this may balance this vertical centering.

Alternatively just look up how to have top aligned content in a flex box.

But yeah CSS is very finicky... probably better to separately build a simple HTML skeleton that does exactly what you want and then map that to the Franklin layout.

**Comment by paniash** [comment]
Thank you! I played around your solution and something just clicked perhaps, it seems to work now. Just one more thing, I can't stylize the footer anymore under
```css
.franklin-content .page-foot a {
  color: #EB9B8B;
  text-decoration: none;
}
```

It doesn't take in the color #EB9B8B anymore. Any suggestion what might be the issue?

**Comment by tlienart** [comment]
well `.page-foot` is not inside `.franklin-content` anymore so your selector is too specific.

**Comment by paniash** [comment]
Ah, you're right! Thanks a lot for all your help, I really appreciate it. :-)

**Comment by paniash** [comment]
Ah, you're right! Thanks a lot for all your help, I really appreciate it. :-)
